### ISSUE TITLE
Change color for active link in sub-navigation 

### ISSUE THREAD

**Issue by cecilaki** [okfn/openbudgets#4]
When you're reading [this page](http://okfnlabs.org/openbudgets/about/work-packages/) for example, it feels weird that the active background of the sub-menu is the same color of the green background.. Don't know if there's a better alternative?

<img width="379" alt="capture d ecran 2015-10-13 a 15 18 09" src="https://cloud.githubusercontent.com/assets/6681719/10572685/d51f208e-764a-11e5-9cf3-85b3f0506077.png">

**Comment by smth** [comment]
Done.
