### ISSUE TITLE
Add a OpenBudgets.eu favicon

### ISSUE THREAD

**Issue by cecilaki** [okfn/openbudgets#5]
The OpenBudgets icon would be perfect!

**Comment by smth** [comment]
Already present https://raw.githubusercontent.com/okfn/openbudgets/gh-pages/favicon.ico

I think this will probably become visible once we move over to openbudgets.eu.

**Comment by cecilaki** [comment]
Yes exactly, it now shows the OKI favicon since it's under the okfnlabs.org domain, of course. My bad.
