### ISSUE TITLE
Update Social Media links in the header 

### ISSUE THREAD

**Issue by cecilaki** [okfn/openbudgets#7]
Open in new window + could the GH link point to [this](https://github.com/os-data/registry/issues) instead of the general OpenBudgets repo? It makes more sense at the moment since we use it as a registry to gather budget datasets.

**Comment by cecilaki** [comment]
@smth  I have now a Facebook page link for the footer and header. Here it is > https://www.facebook.com/openbudgets/

**Comment by smth** [comment]
All done.
