### ISSUE TITLE
Set up the partners page

### ISSUE THREAD

**Issue by cecilaki** [okfn/openbudgets#8]
high priority

**Comment by smth** [comment]
Looks like this has already been done https://github.com/okfn/openbudgets/pull/2/files  or does it need more work?

**Comment by cecilaki** [comment]
It definitely needs more work. In the brief, I refer to a gallery of logos with links to a separate page for each partner when you click the image / title - Something similar to the image gallery in the [opendata handbook](http://opendatahandbook.org/resources/) would work fine.

**Comment by smth** [comment]
How's this? http://openbudgets.eu/about/partners/

The links are still all external, but these can now be configured in this file https://github.com/openbudgets/openbudgets.github.io/blob/master/_data/partners.yml (much the same as events)

**Comment by smth** [comment]
Are you happy for me to close this @cecilaki ?

**Comment by cecilaki** [comment]
I am happy to close this, yes!

**Comment by smth** [comment]
Awesome.
