### ISSUE TITLE
Transfer code from okfn labs to openbudgets.eu repo 

### ISSUE THREAD

**Issue by cecilaki** [okfn/openbudgets#9]
The correct URL is pointing in [this repo](https://github.com/openbudgets/openbudgets.github.io)

**Comment by smth** [comment]
@cecilaki if you'd like me to do this, I think I will need to be added to the openbudgets org.

**Comment by cecilaki** [comment]
You mean the openbudget.eu repo? If it's the case yes, and override the existing files.

**Comment by smth** [comment]
I mean https://github.com/openbudgets or I can just do a pull request.

**Comment by cecilaki** [comment]
I guess so.. I mean it will create a new repo or will replace the current https://github.com/openbudgets/openbudgets.github.io ?

**Comment by smth** [comment]
Is that a "guess so" you'll add me to the org, or "guess so" I should do a pull request? :p

No need to create a new repo. We can archive the current site in it's own branch (if desired), and replace current code with mine. I'm a little confused as to how it is working at the moment though.. there doesn't appear to be a gh-pages branch..

**Comment by cecilaki** [comment]
Added you :) I meant I thought the gh-pages branch was this one > https://github.com/openbudgets/openbudgets.github.io (even tough it's written it's the staging website, it's not - it has the correct configuration )

**Comment by smth** [comment]
That's great, thanks.

I can see now that it is configured to use `master` for GitHub Pages.

**Comment by smth** [comment]
Done.
